/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppMemoriesRouteImport } from './routes/_app.memories'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppExperiencesRouteImport } from './routes/_app.experiences'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreativityRouteImport } from './routes/_app.creativity'
import { Route as AppExperiencesSlugRouteImport } from './routes/_app.experiences.$slug'
import { Route as AppCreativityCategoryRouteImport } from './routes/_app.creativity.$category'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppExperiencesRoute = AppExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreativityRoute = AppCreativityRouteImport.update({
  id: '/creativity',
  path: '/creativity',
  getParentRoute: () => AppRoute,
} as any)
const AppExperiencesSlugRoute = AppExperiencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppExperiencesRoute,
} as any)
const AppCreativityCategoryRoute = AppCreativityCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => AppCreativityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/creativity': typeof AppCreativityRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/discover': typeof AppDiscoverRoute
  '/experiences': typeof AppExperiencesRouteWithChildren
  '/journal': typeof AppJournalRoute
  '/memories': typeof AppMemoriesRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/creativity/$category': typeof AppCreativityCategoryRoute
  '/experiences/$slug': typeof AppExperiencesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/creativity': typeof AppCreativityRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/discover': typeof AppDiscoverRoute
  '/experiences': typeof AppExperiencesRouteWithChildren
  '/journal': typeof AppJournalRoute
  '/memories': typeof AppMemoriesRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/creativity/$category': typeof AppCreativityCategoryRoute
  '/experiences/$slug': typeof AppExperiencesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/creativity': typeof AppCreativityRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/experiences': typeof AppExperiencesRouteWithChildren
  '/_app/journal': typeof AppJournalRoute
  '/_app/memories': typeof AppMemoriesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/creativity/$category': typeof AppCreativityCategoryRoute
  '/_app/experiences/$slug': typeof AppExperiencesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/creativity'
    | '/dashboard'
    | '/discover'
    | '/experiences'
    | '/journal'
    | '/memories'
    | '/settings'
    | '/skills'
    | '/creativity/$category'
    | '/experiences/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/creativity'
    | '/dashboard'
    | '/discover'
    | '/experiences'
    | '/journal'
    | '/memories'
    | '/settings'
    | '/skills'
    | '/creativity/$category'
    | '/experiences/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/creativity'
    | '/_app/dashboard'
    | '/_app/discover'
    | '/_app/experiences'
    | '/_app/journal'
    | '/_app/memories'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/creativity/$category'
    | '/_app/experiences/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memories': {
      id: '/_app/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experiences': {
      id: '/_app/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof AppExperiencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creativity': {
      id: '/_app/creativity'
      path: '/creativity'
      fullPath: '/creativity'
      preLoaderRoute: typeof AppCreativityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experiences/$slug': {
      id: '/_app/experiences/$slug'
      path: '/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof AppExperiencesSlugRouteImport
      parentRoute: typeof AppExperiencesRoute
    }
    '/_app/creativity/$category': {
      id: '/_app/creativity/$category'
      path: '/$category'
      fullPath: '/creativity/$category'
      preLoaderRoute: typeof AppCreativityCategoryRouteImport
      parentRoute: typeof AppCreativityRoute
    }
  }
}

interface AppCreativityRouteChildren {
  AppCreativityCategoryRoute: typeof AppCreativityCategoryRoute
}

const AppCreativityRouteChildren: AppCreativityRouteChildren = {
  AppCreativityCategoryRoute: AppCreativityCategoryRoute,
}

const AppCreativityRouteWithChildren = AppCreativityRoute._addFileChildren(
  AppCreativityRouteChildren,
)

interface AppExperiencesRouteChildren {
  AppExperiencesSlugRoute: typeof AppExperiencesSlugRoute
}

const AppExperiencesRouteChildren: AppExperiencesRouteChildren = {
  AppExperiencesSlugRoute: AppExperiencesSlugRoute,
}

const AppExperiencesRouteWithChildren = AppExperiencesRoute._addFileChildren(
  AppExperiencesRouteChildren,
)

interface AppRouteChildren {
  AppCreativityRoute: typeof AppCreativityRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppExperiencesRoute: typeof AppExperiencesRouteWithChildren
  AppJournalRoute: typeof AppJournalRoute
  AppMemoriesRoute: typeof AppMemoriesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreativityRoute: AppCreativityRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppExperiencesRoute: AppExperiencesRouteWithChildren,
  AppJournalRoute: AppJournalRoute,
  AppMemoriesRoute: AppMemoriesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
